# Generated by Django 6.0 on 2025-12-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('vehicle_make_model', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField()),
                ('registration_number', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('vin_chassis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('service_description', models.TextField()),
                ('serviced_recently', models.BooleanField(default=False)),
                ('preferred_service_date', models.DateField()),
                ('additional_concerns', models.TextField(blank=True, null=True)),
                ('confirmation', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
            ],
        ),
    ]
